# Generated by Django 5.1.6 on 2025-02-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="seo_analysis",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="seo_score",
            field=models.IntegerField(default=0),
        ),
    ]
