# Generated by Django 5.1.6 on 2025-02-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blog_cornerstone_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="keyphrase",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
