# Generated by Django 4.2.4 on 2024-02-06 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDashboardModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("module", models.CharField(max_length=255, verbose_name="module")),
                (
                    "app_label",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="application name"
                    ),
                ),
                ("column", models.PositiveIntegerField(verbose_name="column")),
                ("order", models.IntegerField(verbose_name="order")),
                ("settings", models.TextField(blank=True, default="", verbose_name="settings")),
                ("children", models.TextField(blank=True, default="", verbose_name="children")),
                ("collapsed", models.BooleanField(default=False, verbose_name="collapsed")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user dashboard module",
                "verbose_name_plural": "user dashboard modules",
                "ordering": ("column", "order"),
            },
        ),
        migrations.CreateModel(
            name="PinnedApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("app_label", models.CharField(max_length=255, verbose_name="application name")),
                (
                    "date_add",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date created"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "pinned application",
                "verbose_name_plural": "pinned applications",
                "ordering": ("date_add",),
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "date_add",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date created"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "bookmark",
                "verbose_name_plural": "bookmarks",
                "ordering": ("date_add",),
            },
        ),
    ]
