# Generated by Django 4.2.4 on 2024-01-11 02:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AffiliateProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("program_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProductSubCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sub_category_name", models.CharField(max_length=255)),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.productcategory"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AffiliateProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("product_description", models.TextField()),
                ("product_image", models.URLField(blank=True, null=True)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("affiliate_link", models.URLField()),
                (
                    "affiliate_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.affiliateprogram"
                    ),
                ),
                (
                    "product_sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.productsubcategory",
                    ),
                ),
            ],
        ),
    ]
