# Generated by Django 4.2.4 on 2024-01-19 04:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AffiliateProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("product_description", models.TextField()),
                ("product_image", models.URLField(blank=True, null=True)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("affiliate_link", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Affiliate Product",
                "verbose_name_plural": "Affiliate Products",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AffiliateProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("program_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PinterestBoard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("board_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PinterestPin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pin_name", models.CharField(max_length=100)),
                ("pin_description", models.TextField()),
                ("pin_image", models.URLField(blank=True, null=True)),
                ("pin_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pin_link", models.URLField()),
                ("pin_image_size", models.PositiveIntegerField(blank=True, null=True)),
                ("pin_image_mime_type", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pin_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.pinterestboard"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.affiliateproduct",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="affiliate_program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.affiliateprogram"
            ),
        ),
        migrations.AddField(
            model_name="affiliateproduct",
            name="pinterest_board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.pinterestboard",
            ),
        ),
    ]
