# Generated by Django 4.2.4 on 2024-01-18 19:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinterestBoard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("board_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PinterestPin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pin_name", models.CharField(max_length=255)),
                ("pin_description", models.TextField()),
                ("pin_image", models.URLField(blank=True, null=True)),
                ("pin_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pin_link", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pin_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.pinterestboard"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="productsubcategory",
            name="product_category",
        ),
        migrations.RemoveField(
            model_name="affiliateproduct",
            name="product_sub_category",
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
        migrations.DeleteModel(
            name="ProductSubCategory",
        ),
    ]
