# Generated by Django 4.2.4 on 2024-01-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_pinterestboard_pinterestpin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pinterestpin",
            name="pin_name",
            field=models.CharField(max_length=100),
        ),
    ]
