# Generated by Django 4.2.4 on 2024-02-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_affiliatecategory_affiliateproduct_amazon_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliatecategory",
            name="category_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
