# Generated by Django 4.2.4 on 2024-02-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_affiliatecategory_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliateproduct",
            name="amazon_product_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
