# Generated by Django 4.2.4 on 2024-02-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_affiliateproduct_amazon_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliateproduct",
            name="affiliate_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="affiliateproduct",
            name="product_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
