# Generated by Django 4.2.4 on 2024-01-18 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_affiliateproduct_pinterest_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinterestpin",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.affiliateproduct",
            ),
        ),
    ]
