# Generated by Django 4.2.4 on 2024-01-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_pinterestpin_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="pinterestpin",
            name="pin_image_mime_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pinterestpin",
            name="pin_image_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
