# Generated by Django 4.2.4 on 2024-02-06 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_affiliateproduct_previous_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affiliateproduct",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Affiliate Product",
                "verbose_name_plural": "Affiliate Products",
            },
        ),
    ]
